name: Kernel Config - Samsung

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a12:
    name: "Samsung-${{ matrix.branch }}-${{ matrix.kernel_version }}-${{ matrix.android_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
 #         - branch: "SM-S928B-Oneui7"
 #           android_version: "android14"
 #           kernel_version: "6.1"
          - branch: "SM-S928B-Oneui8"
            android_version: "android14"
            kernel_version: "6.1"
#          - branch: "SM-A546B"
#            android_version: "android13"
#            kernel_version: "5.15"
#          - branch: "SM-A546E"
#            android_version: "android13"
#            kernel_version: "5.15"
#          - branch: "SM-X916B"
#            android_version: "android13"
#            kernel_version: "5.15"
#          - branch: "SM-A366B"
#            android_version: "android15"
#            kernel_version: "6.6"
#          - branch: "SM-F946N"
#            android_version: "android13"
#            kernel_version: "5.15"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      branch: ${{ matrix.branch }}

